In [105]:
import pandas as pd 
import numpy as np 

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

In [108]:
df.shape

(891, 12)

In [110]:
list(df.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [111]:
df.isnull()

     PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
0          False     False   False  False  ...   False  False   True     False
1          False     False   False  False  ...   False  False  False     False
2          False     False   False  False  ...   False  False   True     False
3          False     False   False  False  ...   False  False  False     False
4          False     False   False  False  ...   False  False   True     False
..           ...       ...     ...    ...  ...     ...    ...    ...       ...
886        False     False   False  False  ...   False  False   True     False
887        False     False   False  False  ...   False  False  False     False
888        False     False   False  False  ...   False  False   True     False
889        False     False   False  False  ...   False  False  False     False
890        False     False   False  False  ...   False  False   True     False

[891 rows x 12 columns]

In [136]:
missing_count = df.isnull().sum()
missing_percent = df.isnull().sum() / df.shape[0] * 100

missing_table = pd.DataFrame({
    'missing': missing_count,
    'missing_%': missing_percent.round(2)
})

missing_table.sort_values('missing', ascending=False)

             missing  missing_%
Cabin            687      77.10
Age              177      19.87
Embarked           2       0.22
PassengerId        0       0.00
Survived           0       0.00
Pclass             0       0.00
Name               0       0.00
Sex                0       0.00
SibSp              0       0.00
Parch              0       0.00
Ticket             0       0.00
Fare               0       0.00

In [137]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [150]:
df[df['Pclass'] == 1]

     PassengerId  Survived  Pclass  ...     Fare        Cabin  Embarked
1              2         1       1  ...  71.2833          C85         C
3              4         1       1  ...  53.1000         C123         S
6              7         0       1  ...  51.8625          E46         S
11            12         1       1  ...  26.5500         C103         S
23            24         1       1  ...  35.5000           A6         S
..           ...       ...     ...  ...      ...          ...       ...
871          872         1       1  ...  52.5542          D35         S
872          873         0       1  ...   5.0000  B51 B53 B55         S
879          880         1       1  ...  83.1583          C50         C
887          888         1       1  ...  30.0000          B42         S
889          890         1       1  ...  30.0000         C148         C

[216 rows x 12 columns]

In [156]:
df[(df['Sex'] == 'male') & (df['Age'] > 60)]['Survived'].sum()

np.int64(2)

In [167]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1

In [168]:
df['family_size'].value_counts()

family_size
1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: count, dtype: int64

In [176]:
df['is_alone'] = df['family_size'] == 1

In [178]:
df.groupby('is_alone')['Survived'].mean()

is_alone
False    0.505650
True     0.303538
Name: Survived, dtype: float64

In [180]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [186]:
df['Age_filled'] = df['Age'].fillna(df['Age'].median()).round(0)

In [187]:
df

     PassengerId  Survived  Pclass  ... family_size is_alone  Age_filled
0              1         0       3  ...           2    False        22.0
1              2         1       1  ...           2    False        38.0
2              3         1       3  ...           1     True        26.0
3              4         1       1  ...           2    False        35.0
4              5         0       3  ...           1     True        35.0
..           ...       ...     ...  ...         ...      ...         ...
886          887         0       2  ...           1     True        27.0
887          888         1       1  ...           1     True        19.0
888          889         0       3  ...           4    False        30.0
889          890         1       1  ...           1     True        26.0
890          891         0       3  ...           1     True        32.0

[891 rows x 17 columns]

In [194]:
df['Age'] = df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))
print(f'Nan was: {df['Age'].isnull().sum()}')

Nan was: 0

In [195]:
df['Fare'].sort_values(ascending=False)

258    512.3292
737    512.3292
679    512.3292
88     263.0000
27     263.0000
         ...
633      0.0000
413      0.0000
822      0.0000
732      0.0000
674      0.0000
Name: Fare, Length: 891, dtype: float64

In [203]:
df

     PassengerId  Survived  Pclass  ... family_size is_alone  Age_filled
0              1         0       3  ...           2    False        22.0
1              2         1       1  ...           2    False        38.0
2              3         1       3  ...           1     True        26.0
3              4         1       1  ...           2    False        35.0
4              5         0       3  ...           1     True        35.0
..           ...       ...     ...  ...         ...      ...         ...
886          887         0       2  ...           1     True        27.0
887          888         1       1  ...           1     True        19.0
888          889         0       3  ...           4    False        30.0
889          890         1       1  ...           1     True        26.0
890          891         0       3  ...           1     True        32.0

[891 rows x 17 columns]

In [210]:
len(
    df[(df['Sex'] == 'female') & 
    (df['Age'] > 40) & 
    (df["Pclass"] == 1) & 
    (df['Survived'] == 1)])

25